name: "✨ Feature Request"
description: Request a new feature or improvement
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature would you like to see?
      description: Describe the feature or improvement you’re proposing.
      placeholder: "e.g. Add support for XYZ"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any ideas on how it could work?
      description: (Optional) If you have thoughts on implementation or UI/UX, share them here.
      placeholder: "e.g. XYZ could be triggered with a shortcut"
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I checked existing issues to avoid duplicates
          required: true
