name: Build Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and setup the python version
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync --all-groups
          uv tool install pyinstaller

      - name: Build standalone binary
        run: |
          uvx pyinstaller torrra.spec

      - name: Rename binary by platform
        shell: bash
        run: |
          mkdir -p dist-out
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            cp dist/torrra dist-out/torrra-linux
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            cp dist/torrra.exe dist-out/torrra.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            cp dist/torrra dist-out/torrra-macos
          fi

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist-out/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
